INSERT INTO carts (customer_id, product_id, qty) VALUES (1, 1, 5);
INSERT INTO carts (customer_id, product_id, qty) VALUES (1, 2, 2);
INSERT INTO carts (customer_id, product_id, qty) VALUES (1, 3, 3);
INSERT INTO carts (customer_id, product_id, qty) VALUES (1, 4, 1);
INSERT INTO carts (customer_id, product_id, qty) VALUES (2, 1, 2);
INSERT INTO carts (customer_id, product_id, qty) VALUES (3, 2, 1);
INSERT INTO carts (customer_id, product_id, qty) VALUES (4, 2, 4);
INSERT INTO carts (customer_id, product_id, qty) VALUES (4, 3, 1);
INSERT INTO carts (customer_id, product_id, qty) VALUES (5, 3, 3);