INSERT INTO products (category_id, name, description, price, stock, image, category_id) VALUES (1, 'ViveHealth 3 Wheel Mobility Schooter', 1849.00, 10, 'Red_3wheel_Basket.PNG', '
  Top Speed: 3.70 mph
  Maximum Drive Range Per Charge: 12.4 miles
  Heaviest Piece: 29 lbs.
  Weight Capacity: 265 lbs.
  Total Weight: 77 lbs.');
INSERT INTO products (category_id, name, description, price, stock, image, category_id) VALUES (1, 'Drive S38601 Bobcat 3 Wheel Scooter', 1113.69, 6, 'Drive_S38601_3wheel.PNG', 'The Bobcat 3 Wheel Compact Scooter by Drive Medical is ideal for indoor and outdoor use and is lightweight and easy to operate. It has a 32.2" turning radius, with a top speed of 4 mph and a cruising range of 7.5 miles. It comes in a convenient, compact 4 piece design allows for easy tool free assembly and disassembly. The comfortable, height adjustable seat comes with flip back adjustable arms and anti-tipples to ensure users comfort and safety. The large carry basket provides a safe storage space for personal items and the tiller folds down for easy storage. If you are looking for added product protection, purchase the additional warranty coverage by adding Drive Medicals Piece of Mind protection to your scooter.');
INSERT INTO products (category_id, name, description, price, stock, image, category_id) VALUES (2, 'Medline Adult Toothbrush 30 Tuft', 13.53, 200, 'MDS136000.PNG', 'Medline Adult Toothbrush 30 Tuft');
INSERT INTO products (category_id, name, description, price, stock, image, category_id) VALUES (2, 'DenTips Oral Swabsticks 6"', 70.91, 100, 'MDS096202.PNG', 'DENTIP ORAL SWAB UNTREATED 6" INDIV WRAP');
INSERT INTO products (category_id, name, description, price, stock, image, category_id) VALUES (3, 'ENERGIZER L675ZA-8ZM RAYOVAC HEARING AID BATTERIES #675 PK/8', 15.99, 130, 'RAYOVAC_L675ZA-8ZM_BATTERY_675__87636.PNG', 'Hearing Aid Battery L675ZA-8ZM is a popular battery for behind-the-ear hearing aids. All manufacturers color code this battery blue for easy identification. However this should not be confused with the high power ZA675P cochlear implant batteries that are also colour coded blue.');
INSERT INTO products (category_id, name, description, price, stock, image, category_id) VALUES (3, 'Revamp Progloss Perfect Blow Dryer Volume & Shine Brush', 239.99, 440, 'dr-2000product1__11588__30040__83552.PNG', 'Powerful drying and styling combined into one simple hair tool. The Revamp Progloss Perfect Blow Dry Volume and Shine Air Styler dries, detangles, smooths and styles your hair in just one pass. The oval ceramic barrel of the brush works to smooth and style hair, whilst the rounded edges add volume at the root, to help you create a salon-quality blow-dry at home. To ensure frizz-free styling, this multifunctional styler features 4 ionic jet emitters and a ceramic barrel. Customize your styling experience with 3 Heat/Speed Settings, including a cool option to set your hairstyles in place. The lightweight design and 9 foot salon swivel cable allow for quick and easy styling, with additional flexibility. Infused with Progloss super smooth oils for enhanced shine.');
