DROP TABLE IF EXISTS addresses CASCADE;

CREATE TABLE addresses (
  id SERIAL PRIMARY KEY NOT NULL,
  customer_id INTEGER REFERENCES customers (id) ON DELETE CASCADE,
  street VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  province VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  postal VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  billing BOOLEAN NOT NULL
);