DROP TABLE IF EXISTS carts CASCADE;

CREATE TABLE carts (
  id SERIAL PRIMARY KEY NOT NULL,
  customer_id INTEGER REFERENCES customers (id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products (id) ON DELETE CASCADE,
  qty INTEGER NOT NULL
);